# Copyright (C) 2014-2020 Scandy
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.

# Do not distribute this file.

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Roux example app built on Qt for Unix systems")
set(CPACK_PACKAGE_VENDOR "Scandy")
set(CPACK_PACKAGE_CONTACT "support@scandy.co")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/doc/scandy_logo.png")

if(ENABLE_IOS)
  set(CPACK_SYSTEM_NAME "iOS")
elseif(LINUX_ARM)
  set(CPACK_SYSTEM_NAME "arm-linux-gnueabihf")
else(LINUX)
  set(CPACK_SYSTEM_NAME "linux-x86_64")
endif()

set(CPACK_PACKAGE_VERSION_MAJOR "${Roux_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${Roux_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${Roux_VERSION_PATCH}.${Roux_VERSION_COUNT}")
set(CPACK_PACKAGE_VERSION "${Roux_VERSION_FULL}")

set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")

set(CPACK_GENERATOR "ZIP")
include(CPack)
